### ISSUE TITLE
Object missing

### ISSUE THREAD

**Issue by olderbag** [SebastianSchultz/ioBroker.lgtv2011#4]
In the README of the adapter i find the following example:

`setState('lgtv.0.popup', 'Some text!');

This will show a popup with the text "Some text!" on the TV. You can use HTML linebreaks (br) in the `text.`

However, in objects.lgtv11.0 there's no object named popup.

**Comment by SebastianSchultz** [comment]
I'm very sorry, that's a mistake in the readme.
I had copied parts of the WebOS LG TV Adapter readme. In WebOS TVs you have the ability to show this popup. On the older TV you cannot show a popup.

However I updated the readme. Thanks for the information!
