### ISSUE TITLE
Please add status information 

### ISSUE THREAD

**Issue by HReimann** [SebastianSchultz/ioBroker.lgtv2011#7]
sorry i haven't to less programming skill to do it by my own.

But it seems possible  that the Volume Status, etc. could be readeable by the iobroker based on this Information. 
http://developer.lgappstv.com/TV_HELP/topic/lge.tvsdk.references.book/html/UDAP/UDAP/Query%20Controller%20Host1.htm?path=4_0_1_1_3#_Toc353804424 
The Queries that there was written in the link are:
    **-  Current channel information (Controller >> Host)**
    -  Entire channels list (Controller >> Host)
    -  Operation mode of the Host UI (Controller >> Host)
    **-  Volume information of the Host (Controller >> Host)**
    -  Obtaining the capture image of the Host (Controller >> Host)
    -  3D mode of the Host (Controller >> Host)
Could you please try to extend the Code for the bolded Queries that was my favourites.
Kindly regards
Holger

**Comment by SebastianSchultz** [comment]
Hello Holger,

currently I have less time to work on it but I have it on my to do list :)
So I will work on that.

**Comment by SebastianSchultz** [comment]
Hello Holger,

can you please update your posted link? It returns me a 404 error :(

**Comment by HReimann** [comment]
Hello Sebastian,
i hope this link work http://webostv.developer.lge.com/application/files/1214/7919/6747/NetCast_-_UDAP.pdf
Note from LG  "UDAP 2.0 is only supported in NetCast 3.0 (LG Smart TV models released in 2012) and NetCast 4.0 (LG Smart TV models released in 2013)"

Thank you for your great work

**Comment by SebastianSchultz** [comment]
Will try to work on that on the next release.

**Comment by SebastianSchultz** [comment]
Hello Holger,

can you please help me in development/testing?
Attached you'll find a new main.js. Can you please replace the current main.js with this one (please make backup before) and stop the adapter?
Then set the adapter to debug level and start the adapter.

I hope we'll get current tv channel informtion as http request in the debug log. Can you please post the log here?

[main.zip](https://github.com/SebastianSchultz/ioBroker.lgtv11/files/3354387/main.zip)

**Comment by HReimann** [comment]
Hello Sebastian,
thanks for the file.
I made a quick test with the Adapter but it seams that the Connection could not established with the old secret key.
at first a error appears  "Error: on RequestSessionKey Error: connect" 
fixed this with nes SessionKey. 
But after that i had further Errro you can see it on the attached log.

[LG11.log](https://github.com/SebastianSchultz/ioBroker.lgtv11/files/3355833/LG11.log)

**Comment by SebastianSchultz** [comment]
OK thanks, I will investigate this. Please use your "old" main.js file.

**Comment by HReimann** [comment]
I just see that also some Errors from outer LG11.
Attached the new log.

[LG11_2.log](https://github.com/SebastianSchultz/ioBroker.lgtv11/files/3356699/LG11_2.log)

**Comment by SebastianSchultz** [comment]
Thanks for the log. Do you have entered your tv in adapter config by ip address or hostname?
if ip address so it seems there is a bug in http dns resolution?!
I must investigate this further.

**Comment by HReimann** [comment]
Hello Stefan, it is an IP Entry.
